# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:58:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, constr


class Examination(BaseModel):
    month: constr(min_length=1) = Field(..., examples=['MARCH'])
    name: constr(min_length=1) = Field(
        ..., examples=['SENION SCHOOL CERTIFICATE EXAMINATION']
    )
    year: constr(min_length=1) = Field(..., examples=[2019])


class Subject(BaseModel):
    code: constr(min_length=1) = Field(..., examples=[30])
    gp: str = Field(..., examples=[''])
    gpMax: str = Field(..., examples=[''])
    grade: constr(min_length=1) = Field(..., examples=['A2'])
    marksMax: int = Field(..., examples=[''])
    marksMaxPractical: int = Field(..., examples=[''])
    marksMaxTheory: int = Field(..., examples=[''])
    marksPractical: int = Field(..., examples=[17])
    marksTheory: int = Field(..., examples=[70])
    marksTotal: int = Field(..., examples=[87])
    name: constr(min_length=1) = Field(..., examples=['ECONOMICS'])


class Performance(BaseModel):
    Subjects: List[Subject]
    cgpa: str = Field(..., examples=[''])
    cgpaMax: str = Field(..., examples=[''])
    grade: str = Field(..., examples=[''])
    marksMax: str = Field(..., examples=[''])
    marksTotal: str = Field(..., examples=[''])
    percentage: str = Field(..., examples=[''])
    result: constr(min_length=1) = Field(..., examples=['PASS'])
    resultDate: constr(min_length=1) = Field(..., examples=['02-05-2019'])
    updateDate: str = Field(..., examples=[''])


class School(BaseModel):
    code: constr(min_length=1) = Field(..., examples=[20020])
    name: constr(min_length=1) = Field(..., examples=['DELHI PUBLIC SCHOOL GURGAON'])


class CertificateData(BaseModel):
    Examination_1: Examination = Field(..., alias='Examination')
    Performance_1: Performance = Field(..., alias='Performance')
    School_1: School = Field(..., alias='School')


class Address(BaseModel):
    country: constr(min_length=1) = Field(..., examples=['IN'])
    district: str = Field(..., examples=[''])
    house: str = Field(..., examples=[''])
    landmark: str = Field(..., examples=[''])
    line1: str = Field(..., examples=[''])
    line2: str = Field(..., examples=[''])
    locality: str = Field(..., examples=[''])
    pin: str = Field(..., examples=[''])
    state: str = Field(..., examples=[''])
    type: str = Field(..., examples=[''])
    vtc: str = Field(..., examples=[''])


class Organization(BaseModel):
    Address_1: Address = Field(..., alias='Address')
    code: str = Field(..., examples=[''])
    name: constr(min_length=1) = Field(
        ..., examples=['Central Board of Secondary Education']
    )
    tin: str = Field(..., examples=[''])
    type: constr(min_length=1) = Field(..., examples=['CG'])
    uid: str = Field(..., examples=[''])


class IssuedBy(BaseModel):
    Organization_1: Organization = Field(..., alias='Organization')


class Address1(BaseModel):
    country: constr(min_length=1) = Field(..., examples=['IN'])
    district: str = Field(..., examples=[''])
    house: str = Field(..., examples=[''])
    landmark: str = Field(..., examples=[None])
    line1: str = Field(..., examples=[''])
    line2: str = Field(..., examples=[''])
    locality: str = Field(..., examples=[''])
    pin: str = Field(..., examples=[''])
    state: str = Field(..., examples=[''])
    type: constr(min_length=1) = Field(..., examples=['permanent'])
    vtc: str = Field(..., examples=[''])


class Photo(BaseModel):
    format: str


class Person(BaseModel):
    Address: Address1
    Photo_1: Photo = Field(..., alias='Photo')
    category: constr(min_length=1) = Field(..., examples=['SC'])
    disabilityStatus: str = Field(..., examples=[''])
    dob: constr(min_length=1) = Field(..., examples=['01-10-1988'])
    email: str = Field(..., examples=[''])
    gender: str = Field(..., examples=[''])
    maritalStatus: str = Field(..., examples=[''])
    motherName: constr(min_length=1) = Field(..., examples=['SUNITA DEVI'])
    name: constr(min_length=1) = Field(..., examples=['ANAND KUMAR'])
    phone: str = Field(..., examples=[''])
    religion: str = Field(..., examples=[''])
    swd: constr(min_length=1) = Field(..., examples=['PRAMOD KUMAR'])
    swdIndicator: constr(min_length=1) = Field(..., examples=['S'])
    title: str = Field(..., examples=[''])
    uid: str = Field(..., examples=[''])


class IssuedTo(BaseModel):
    Person_1: Person = Field(..., alias='Person')


class AcademicCertificateSchema(BaseModel):
    CertificateData_1: CertificateData = Field(..., alias='CertificateData')
    IssuedBy_1: IssuedBy = Field(..., alias='IssuedBy')
    IssuedTo_1: IssuedTo = Field(..., alias='IssuedTo')
    issueDate: str = Field(..., examples=[' '])
    issuedAt: str = Field(..., examples=[''])
    language: constr(min_length=1) = Field(..., examples=[99])
    name: constr(min_length=1) = Field(..., examples=['Secondary School Certificate'])
    number: int = Field(..., examples=[1100044])
    status: constr(min_length=1) = Field(..., examples=['A'])
    type: str = Field(..., examples=['SSCER'])
    validFromDate: str = Field(..., examples=[' '])


class Data(BaseModel):
    id: constr(min_length=1)


class DataConsumer(BaseModel):
    id: constr(min_length=1)


class DataProvider(BaseModel):
    id: constr(min_length=1)


class DateRange(BaseModel):
    from_: datetime = Field(
        ...,
        alias='from',
        description='Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ',
    )
    to: datetime = Field(
        ...,
        description='Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ',
    )


class Frequency(BaseModel):
    repeats: float
    unit: constr(min_length=1)
    value: float


class Permission(BaseModel):
    access: constr(min_length=1)
    dateRange: DateRange
    frequency: Frequency


class Purpose(BaseModel):
    description: constr(min_length=1)


class User(BaseModel):
    email: constr(min_length=1)
    idNumber: constr(min_length=1)
    idType: constr(min_length=1)
    mobile: constr(min_length=1)


class Consent(BaseModel):
    consentId: UUID = Field(
        ...,
        description='A unique consent id in UUID format.',
        examples=['ea9c43aa-7f5a-4bf3-a0be-e1caa24737ba'],
    )
    data: Data
    dataConsumer: DataConsumer
    dataProvider: DataProvider
    permission: Permission
    purpose: Purpose
    timestamp: datetime = Field(
        ...,
        description='Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ',
    )
    user: User


class Signature(BaseModel):
    signature: str


class ConsentArtifactSchema(BaseModel):
    consent: Consent
    signature: Signature


class CertificateParameters(BaseModel):
    RefNo: str = Field(..., description='Reference No.', examples=['PRTC/2017/84891'])
    TokenNo: str = Field(..., description='Token No.', examples=['B2881A75'])


class Format(Enum):
    pdf = 'pdf'


class ChcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class ChcerCertificatePostResponse(BaseModel):
    error: Optional[Error] = None
    errorDescription: Optional[ErrorDescription] = None


class Error1(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription1(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class ChcerCertificatePostResponse1(BaseModel):
    error: Optional[Error1] = None
    errorDescription: Optional[ErrorDescription1] = None


class Error2(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription2(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class ChcerCertificatePostResponse2(BaseModel):
    error: Optional[Error2] = None
    errorDescription: Optional[ErrorDescription2] = None


class Error3(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription3(Enum):
    Internal_server_error = 'Internal server error'


class ChcerCertificatePostResponse3(BaseModel):
    error: Optional[Error3] = None
    errorDescription: Optional[ErrorDescription3] = None


class Error4(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription4(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class ChcerCertificatePostResponse4(BaseModel):
    error: Optional[Error4] = None
    errorDescription: Optional[ErrorDescription4] = None


class Error5(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription5(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class ChcerCertificatePostResponse5(BaseModel):
    error: Optional[Error5] = None
    errorDescription: Optional[ErrorDescription5] = None


class Error6(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription6(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class ChcerCertificatePostResponse6(BaseModel):
    error: Optional[Error6] = None
    errorDescription: Optional[ErrorDescription6] = None


class DncerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error7(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription7(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class DncerCertificatePostResponse(BaseModel):
    error: Optional[Error7] = None
    errorDescription: Optional[ErrorDescription7] = None


class Error8(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription8(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class DncerCertificatePostResponse1(BaseModel):
    error: Optional[Error8] = None
    errorDescription: Optional[ErrorDescription8] = None


class Error9(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription9(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class DncerCertificatePostResponse2(BaseModel):
    error: Optional[Error9] = None
    errorDescription: Optional[ErrorDescription9] = None


class Error10(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription10(Enum):
    Internal_server_error = 'Internal server error'


class DncerCertificatePostResponse3(BaseModel):
    error: Optional[Error10] = None
    errorDescription: Optional[ErrorDescription10] = None


class Error11(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription11(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class DncerCertificatePostResponse4(BaseModel):
    error: Optional[Error11] = None
    errorDescription: Optional[ErrorDescription11] = None


class Error12(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription12(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class DncerCertificatePostResponse5(BaseModel):
    error: Optional[Error12] = None
    errorDescription: Optional[ErrorDescription12] = None


class Error13(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription13(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class DncerCertificatePostResponse6(BaseModel):
    error: Optional[Error13] = None
    errorDescription: Optional[ErrorDescription13] = None


class DpcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error14(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription14(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class DpcerCertificatePostResponse(BaseModel):
    error: Optional[Error14] = None
    errorDescription: Optional[ErrorDescription14] = None


class Error15(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription15(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class DpcerCertificatePostResponse1(BaseModel):
    error: Optional[Error15] = None
    errorDescription: Optional[ErrorDescription15] = None


class Error16(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription16(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class DpcerCertificatePostResponse2(BaseModel):
    error: Optional[Error16] = None
    errorDescription: Optional[ErrorDescription16] = None


class Error17(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription17(Enum):
    Internal_server_error = 'Internal server error'


class DpcerCertificatePostResponse3(BaseModel):
    error: Optional[Error17] = None
    errorDescription: Optional[ErrorDescription17] = None


class Error18(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription18(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class DpcerCertificatePostResponse4(BaseModel):
    error: Optional[Error18] = None
    errorDescription: Optional[ErrorDescription18] = None


class Error19(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription19(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class DpcerCertificatePostResponse5(BaseModel):
    error: Optional[Error19] = None
    errorDescription: Optional[ErrorDescription19] = None


class Error20(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription20(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class DpcerCertificatePostResponse6(BaseModel):
    error: Optional[Error20] = None
    errorDescription: Optional[ErrorDescription20] = None


class FslcsCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error21(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription21(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class FslcsCertificatePostResponse(BaseModel):
    error: Optional[Error21] = None
    errorDescription: Optional[ErrorDescription21] = None


class Error22(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription22(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class FslcsCertificatePostResponse1(BaseModel):
    error: Optional[Error22] = None
    errorDescription: Optional[ErrorDescription22] = None


class Error23(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription23(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class FslcsCertificatePostResponse2(BaseModel):
    error: Optional[Error23] = None
    errorDescription: Optional[ErrorDescription23] = None


class Error24(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription24(Enum):
    Internal_server_error = 'Internal server error'


class FslcsCertificatePostResponse3(BaseModel):
    error: Optional[Error24] = None
    errorDescription: Optional[ErrorDescription24] = None


class Error25(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription25(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class FslcsCertificatePostResponse4(BaseModel):
    error: Optional[Error25] = None
    errorDescription: Optional[ErrorDescription25] = None


class Error26(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription26(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class FslcsCertificatePostResponse5(BaseModel):
    error: Optional[Error26] = None
    errorDescription: Optional[ErrorDescription26] = None


class Error27(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription27(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class FslcsCertificatePostResponse6(BaseModel):
    error: Optional[Error27] = None
    errorDescription: Optional[ErrorDescription27] = None


class GrredCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error28(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription28(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class GrredCertificatePostResponse(BaseModel):
    error: Optional[Error28] = None
    errorDescription: Optional[ErrorDescription28] = None


class Error29(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription29(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class GrredCertificatePostResponse1(BaseModel):
    error: Optional[Error29] = None
    errorDescription: Optional[ErrorDescription29] = None


class Error30(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription30(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class GrredCertificatePostResponse2(BaseModel):
    error: Optional[Error30] = None
    errorDescription: Optional[ErrorDescription30] = None


class Error31(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription31(Enum):
    Internal_server_error = 'Internal server error'


class GrredCertificatePostResponse3(BaseModel):
    error: Optional[Error31] = None
    errorDescription: Optional[ErrorDescription31] = None


class Error32(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription32(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class GrredCertificatePostResponse4(BaseModel):
    error: Optional[Error32] = None
    errorDescription: Optional[ErrorDescription32] = None


class Error33(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription33(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class GrredCertificatePostResponse5(BaseModel):
    error: Optional[Error33] = None
    errorDescription: Optional[ErrorDescription33] = None


class Error34(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription34(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class GrredCertificatePostResponse6(BaseModel):
    error: Optional[Error34] = None
    errorDescription: Optional[ErrorDescription34] = None


class IncerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error35(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription35(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class IncerCertificatePostResponse(BaseModel):
    error: Optional[Error35] = None
    errorDescription: Optional[ErrorDescription35] = None


class Error36(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription36(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class IncerCertificatePostResponse1(BaseModel):
    error: Optional[Error36] = None
    errorDescription: Optional[ErrorDescription36] = None


class Error37(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription37(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class IncerCertificatePostResponse2(BaseModel):
    error: Optional[Error37] = None
    errorDescription: Optional[ErrorDescription37] = None


class Error38(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription38(Enum):
    Internal_server_error = 'Internal server error'


class IncerCertificatePostResponse3(BaseModel):
    error: Optional[Error38] = None
    errorDescription: Optional[ErrorDescription38] = None


class Error39(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription39(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class IncerCertificatePostResponse4(BaseModel):
    error: Optional[Error39] = None
    errorDescription: Optional[ErrorDescription39] = None


class Error40(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription40(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class IncerCertificatePostResponse5(BaseModel):
    error: Optional[Error40] = None
    errorDescription: Optional[ErrorDescription40] = None


class Error41(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription41(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class IncerCertificatePostResponse6(BaseModel):
    error: Optional[Error41] = None
    errorDescription: Optional[ErrorDescription41] = None


class IsoalCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error42(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription42(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class IsoalCertificatePostResponse(BaseModel):
    error: Optional[Error42] = None
    errorDescription: Optional[ErrorDescription42] = None


class Error43(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription43(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class IsoalCertificatePostResponse1(BaseModel):
    error: Optional[Error43] = None
    errorDescription: Optional[ErrorDescription43] = None


class Error44(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription44(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class IsoalCertificatePostResponse2(BaseModel):
    error: Optional[Error44] = None
    errorDescription: Optional[ErrorDescription44] = None


class Error45(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription45(Enum):
    Internal_server_error = 'Internal server error'


class IsoalCertificatePostResponse3(BaseModel):
    error: Optional[Error45] = None
    errorDescription: Optional[ErrorDescription45] = None


class Error46(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription46(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class IsoalCertificatePostResponse4(BaseModel):
    error: Optional[Error46] = None
    errorDescription: Optional[ErrorDescription46] = None


class Error47(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription47(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class IsoalCertificatePostResponse5(BaseModel):
    error: Optional[Error47] = None
    errorDescription: Optional[ErrorDescription47] = None


class Error48(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription48(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class IsoalCertificatePostResponse6(BaseModel):
    error: Optional[Error48] = None
    errorDescription: Optional[ErrorDescription48] = None


class LvcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error49(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription49(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class LvcerCertificatePostResponse(BaseModel):
    error: Optional[Error49] = None
    errorDescription: Optional[ErrorDescription49] = None


class Error50(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription50(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class LvcerCertificatePostResponse1(BaseModel):
    error: Optional[Error50] = None
    errorDescription: Optional[ErrorDescription50] = None


class Error51(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription51(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class LvcerCertificatePostResponse2(BaseModel):
    error: Optional[Error51] = None
    errorDescription: Optional[ErrorDescription51] = None


class Error52(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription52(Enum):
    Internal_server_error = 'Internal server error'


class LvcerCertificatePostResponse3(BaseModel):
    error: Optional[Error52] = None
    errorDescription: Optional[ErrorDescription52] = None


class Error53(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription53(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class LvcerCertificatePostResponse4(BaseModel):
    error: Optional[Error53] = None
    errorDescription: Optional[ErrorDescription53] = None


class Error54(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription54(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class LvcerCertificatePostResponse5(BaseModel):
    error: Optional[Error54] = None
    errorDescription: Optional[ErrorDescription54] = None


class Error55(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription55(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class LvcerCertificatePostResponse6(BaseModel):
    error: Optional[Error55] = None
    errorDescription: Optional[ErrorDescription55] = None


class MalcsCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error56(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription56(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class MalcsCertificatePostResponse(BaseModel):
    error: Optional[Error56] = None
    errorDescription: Optional[ErrorDescription56] = None


class Error57(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription57(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class MalcsCertificatePostResponse1(BaseModel):
    error: Optional[Error57] = None
    errorDescription: Optional[ErrorDescription57] = None


class Error58(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription58(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class MalcsCertificatePostResponse2(BaseModel):
    error: Optional[Error58] = None
    errorDescription: Optional[ErrorDescription58] = None


class Error59(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription59(Enum):
    Internal_server_error = 'Internal server error'


class MalcsCertificatePostResponse3(BaseModel):
    error: Optional[Error59] = None
    errorDescription: Optional[ErrorDescription59] = None


class Error60(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription60(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class MalcsCertificatePostResponse4(BaseModel):
    error: Optional[Error60] = None
    errorDescription: Optional[ErrorDescription60] = None


class Error61(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription61(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class MalcsCertificatePostResponse5(BaseModel):
    error: Optional[Error61] = None
    errorDescription: Optional[ErrorDescription61] = None


class Error62(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription62(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class MalcsCertificatePostResponse6(BaseModel):
    error: Optional[Error62] = None
    errorDescription: Optional[ErrorDescription62] = None


class MpkbyCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error63(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription63(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class MpkbyCertificatePostResponse(BaseModel):
    error: Optional[Error63] = None
    errorDescription: Optional[ErrorDescription63] = None


class Error64(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription64(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class MpkbyCertificatePostResponse1(BaseModel):
    error: Optional[Error64] = None
    errorDescription: Optional[ErrorDescription64] = None


class Error65(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription65(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class MpkbyCertificatePostResponse2(BaseModel):
    error: Optional[Error65] = None
    errorDescription: Optional[ErrorDescription65] = None


class Error66(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription66(Enum):
    Internal_server_error = 'Internal server error'


class MpkbyCertificatePostResponse3(BaseModel):
    error: Optional[Error66] = None
    errorDescription: Optional[ErrorDescription66] = None


class Error67(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription67(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class MpkbyCertificatePostResponse4(BaseModel):
    error: Optional[Error67] = None
    errorDescription: Optional[ErrorDescription67] = None


class Error68(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription68(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class MpkbyCertificatePostResponse5(BaseModel):
    error: Optional[Error68] = None
    errorDescription: Optional[ErrorDescription68] = None


class Error69(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription69(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class MpkbyCertificatePostResponse6(BaseModel):
    error: Optional[Error69] = None
    errorDescription: Optional[ErrorDescription69] = None


class ObcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error70(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription70(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class ObcerCertificatePostResponse(BaseModel):
    error: Optional[Error70] = None
    errorDescription: Optional[ErrorDescription70] = None


class Error71(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription71(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class ObcerCertificatePostResponse1(BaseModel):
    error: Optional[Error71] = None
    errorDescription: Optional[ErrorDescription71] = None


class Error72(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription72(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class ObcerCertificatePostResponse2(BaseModel):
    error: Optional[Error72] = None
    errorDescription: Optional[ErrorDescription72] = None


class Error73(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription73(Enum):
    Internal_server_error = 'Internal server error'


class ObcerCertificatePostResponse3(BaseModel):
    error: Optional[Error73] = None
    errorDescription: Optional[ErrorDescription73] = None


class Error74(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription74(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class ObcerCertificatePostResponse4(BaseModel):
    error: Optional[Error74] = None
    errorDescription: Optional[ErrorDescription74] = None


class Error75(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription75(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class ObcerCertificatePostResponse5(BaseModel):
    error: Optional[Error75] = None
    errorDescription: Optional[ErrorDescription75] = None


class Error76(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription76(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class ObcerCertificatePostResponse6(BaseModel):
    error: Optional[Error76] = None
    errorDescription: Optional[ErrorDescription76] = None


class RitinCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error77(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription77(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class RitinCertificatePostResponse(BaseModel):
    error: Optional[Error77] = None
    errorDescription: Optional[ErrorDescription77] = None


class Error78(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription78(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class RitinCertificatePostResponse1(BaseModel):
    error: Optional[Error78] = None
    errorDescription: Optional[ErrorDescription78] = None


class Error79(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription79(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class RitinCertificatePostResponse2(BaseModel):
    error: Optional[Error79] = None
    errorDescription: Optional[ErrorDescription79] = None


class Error80(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription80(Enum):
    Internal_server_error = 'Internal server error'


class RitinCertificatePostResponse3(BaseModel):
    error: Optional[Error80] = None
    errorDescription: Optional[ErrorDescription80] = None


class Error81(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription81(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class RitinCertificatePostResponse4(BaseModel):
    error: Optional[Error81] = None
    errorDescription: Optional[ErrorDescription81] = None


class Error82(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription82(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class RitinCertificatePostResponse5(BaseModel):
    error: Optional[Error82] = None
    errorDescription: Optional[ErrorDescription82] = None


class Error83(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription83(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class RitinCertificatePostResponse6(BaseModel):
    error: Optional[Error83] = None
    errorDescription: Optional[ErrorDescription83] = None


class RmcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error84(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription84(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class RmcerCertificatePostResponse(BaseModel):
    error: Optional[Error84] = None
    errorDescription: Optional[ErrorDescription84] = None


class Error85(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription85(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class RmcerCertificatePostResponse1(BaseModel):
    error: Optional[Error85] = None
    errorDescription: Optional[ErrorDescription85] = None


class Error86(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription86(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class RmcerCertificatePostResponse2(BaseModel):
    error: Optional[Error86] = None
    errorDescription: Optional[ErrorDescription86] = None


class Error87(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription87(Enum):
    Internal_server_error = 'Internal server error'


class RmcerCertificatePostResponse3(BaseModel):
    error: Optional[Error87] = None
    errorDescription: Optional[ErrorDescription87] = None


class Error88(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription88(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class RmcerCertificatePostResponse4(BaseModel):
    error: Optional[Error88] = None
    errorDescription: Optional[ErrorDescription88] = None


class Error89(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription89(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class RmcerCertificatePostResponse5(BaseModel):
    error: Optional[Error89] = None
    errorDescription: Optional[ErrorDescription89] = None


class Error90(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription90(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class RmcerCertificatePostResponse6(BaseModel):
    error: Optional[Error90] = None
    errorDescription: Optional[ErrorDescription90] = None


class RscerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error91(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription91(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class RscerCertificatePostResponse(BaseModel):
    error: Optional[Error91] = None
    errorDescription: Optional[ErrorDescription91] = None


class Error92(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription92(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class RscerCertificatePostResponse1(BaseModel):
    error: Optional[Error92] = None
    errorDescription: Optional[ErrorDescription92] = None


class Error93(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription93(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class RscerCertificatePostResponse2(BaseModel):
    error: Optional[Error93] = None
    errorDescription: Optional[ErrorDescription93] = None


class Error94(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription94(Enum):
    Internal_server_error = 'Internal server error'


class RscerCertificatePostResponse3(BaseModel):
    error: Optional[Error94] = None
    errorDescription: Optional[ErrorDescription94] = None


class Error95(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription95(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class RscerCertificatePostResponse4(BaseModel):
    error: Optional[Error95] = None
    errorDescription: Optional[ErrorDescription95] = None


class Error96(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription96(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class RscerCertificatePostResponse5(BaseModel):
    error: Optional[Error96] = None
    errorDescription: Optional[ErrorDescription96] = None


class Error97(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription97(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class RscerCertificatePostResponse6(BaseModel):
    error: Optional[Error97] = None
    errorDescription: Optional[ErrorDescription97] = None


class ShcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error98(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription98(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class ShcerCertificatePostResponse(BaseModel):
    error: Optional[Error98] = None
    errorDescription: Optional[ErrorDescription98] = None


class Error99(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription99(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class ShcerCertificatePostResponse1(BaseModel):
    error: Optional[Error99] = None
    errorDescription: Optional[ErrorDescription99] = None


class Error100(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription100(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class ShcerCertificatePostResponse2(BaseModel):
    error: Optional[Error100] = None
    errorDescription: Optional[ErrorDescription100] = None


class Error101(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription101(Enum):
    Internal_server_error = 'Internal server error'


class ShcerCertificatePostResponse3(BaseModel):
    error: Optional[Error101] = None
    errorDescription: Optional[ErrorDescription101] = None


class Error102(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription102(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class ShcerCertificatePostResponse4(BaseModel):
    error: Optional[Error102] = None
    errorDescription: Optional[ErrorDescription102] = None


class Error103(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription103(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class ShcerCertificatePostResponse5(BaseModel):
    error: Optional[Error103] = None
    errorDescription: Optional[ErrorDescription103] = None


class Error104(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription104(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class ShcerCertificatePostResponse6(BaseModel):
    error: Optional[Error104] = None
    errorDescription: Optional[ErrorDescription104] = None


class SmcerCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error105(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription105(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class SmcerCertificatePostResponse(BaseModel):
    error: Optional[Error105] = None
    errorDescription: Optional[ErrorDescription105] = None


class Error106(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription106(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class SmcerCertificatePostResponse1(BaseModel):
    error: Optional[Error106] = None
    errorDescription: Optional[ErrorDescription106] = None


class Error107(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription107(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class SmcerCertificatePostResponse2(BaseModel):
    error: Optional[Error107] = None
    errorDescription: Optional[ErrorDescription107] = None


class Error108(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription108(Enum):
    Internal_server_error = 'Internal server error'


class SmcerCertificatePostResponse3(BaseModel):
    error: Optional[Error108] = None
    errorDescription: Optional[ErrorDescription108] = None


class Error109(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription109(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class SmcerCertificatePostResponse4(BaseModel):
    error: Optional[Error109] = None
    errorDescription: Optional[ErrorDescription109] = None


class Error110(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription110(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class SmcerCertificatePostResponse5(BaseModel):
    error: Optional[Error110] = None
    errorDescription: Optional[ErrorDescription110] = None


class Error111(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription111(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class SmcerCertificatePostResponse6(BaseModel):
    error: Optional[Error111] = None
    errorDescription: Optional[ErrorDescription111] = None


class SslcsCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error112(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription112(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class SslcsCertificatePostResponse(BaseModel):
    error: Optional[Error112] = None
    errorDescription: Optional[ErrorDescription112] = None


class Error113(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription113(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class SslcsCertificatePostResponse1(BaseModel):
    error: Optional[Error113] = None
    errorDescription: Optional[ErrorDescription113] = None


class Error114(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription114(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class SslcsCertificatePostResponse2(BaseModel):
    error: Optional[Error114] = None
    errorDescription: Optional[ErrorDescription114] = None


class Error115(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription115(Enum):
    Internal_server_error = 'Internal server error'


class SslcsCertificatePostResponse3(BaseModel):
    error: Optional[Error115] = None
    errorDescription: Optional[ErrorDescription115] = None


class Error116(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription116(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class SslcsCertificatePostResponse4(BaseModel):
    error: Optional[Error116] = None
    errorDescription: Optional[ErrorDescription116] = None


class Error117(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription117(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class SslcsCertificatePostResponse5(BaseModel):
    error: Optional[Error117] = None
    errorDescription: Optional[ErrorDescription117] = None


class Error118(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription118(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class SslcsCertificatePostResponse6(BaseModel):
    error: Optional[Error118] = None
    errorDescription: Optional[ErrorDescription118] = None


class VrwmiCertificatePostRequest(BaseModel):
    certificateParameters: Optional[CertificateParameters] = None
    consentArtifact: Optional[ConsentArtifactSchema] = None
    format: Format = Field(
        ..., description='The format of the certificate in response.'
    )
    txnId: UUID = Field(
        ...,
        description='A unique transaction id for this request in UUID format. It is used for tracking the request.',
        examples=['f7f1469c-29b0-4325-9dfc-c567200a70f7'],
    )


class Error119(Enum):
    missing_parameter = 'missing_parameter'
    invalid_parameter = 'invalid_parameter'
    invalid_format = 'invalid_format'
    invalid_txnid = 'invalid_txnid'
    invalid_consentid = 'invalid_consentid'


class ErrorDescription119(Enum):
    Please_provide_all_mandatory_parameters = 'Please provide all mandatory parameters'
    Bad_request = 'Bad request'
    The_format_parameter_is_invalid = 'The format parameter is invalid'
    The_txnId_parameter_must_be_in_UUID_format = (
        'The txnId parameter must be in UUID format'
    )
    The_consentId_parameter_must_be_in_UUID_format = (
        'The consentId parameter must be in UUID format'
    )


class VrwmiCertificatePostResponse(BaseModel):
    error: Optional[Error119] = None
    errorDescription: Optional[ErrorDescription119] = None


class Error120(Enum):
    invalid_authentication = 'invalid_authentication'
    invalid_authorization = 'invalid_authorization'


class ErrorDescription120(Enum):
    Authentication_failed = 'Authentication failed'
    You_are_not_authorized_to_use_this_API = 'You are not authorized to use this API'


class VrwmiCertificatePostResponse1(BaseModel):
    error: Optional[Error120] = None
    errorDescription: Optional[ErrorDescription120] = None


class Error121(Enum):
    record_not_found = 'record_not_found'
    url_not_found = 'url_not_found'


class ErrorDescription121(Enum):
    No_record_found = 'No record found'
    Your_API_url_or_path_is_incorrect = 'Your API url or path is incorrect'


class VrwmiCertificatePostResponse2(BaseModel):
    error: Optional[Error121] = None
    errorDescription: Optional[ErrorDescription121] = None


class Error122(Enum):
    internal_server_error = 'internal_server_error'


class ErrorDescription122(Enum):
    Internal_server_error = 'Internal server error'


class VrwmiCertificatePostResponse3(BaseModel):
    error: Optional[Error122] = None
    errorDescription: Optional[ErrorDescription122] = None


class Error123(Enum):
    bad_gatewy = 'bad_gatewy'


class ErrorDescription123(Enum):
    Publisher_service_returned_an_invalid_response = (
        'Publisher service returned an invalid response'
    )


class VrwmiCertificatePostResponse4(BaseModel):
    error: Optional[Error123] = None
    errorDescription: Optional[ErrorDescription123] = None


class Error124(Enum):
    service_unavailable = 'service_unavailable'


class ErrorDescription124(Enum):
    Publisher_service_is_temporarily_unavailable = (
        'Publisher service is temporarily unavailable'
    )


class VrwmiCertificatePostResponse5(BaseModel):
    error: Optional[Error124] = None
    errorDescription: Optional[ErrorDescription124] = None


class Error125(Enum):
    gateway_timeout = 'gateway_timeout'


class ErrorDescription125(Enum):
    Publisher_service_did_not_respond_in_time = (
        'Publisher service did not respond in time'
    )


class VrwmiCertificatePostResponse6(BaseModel):
    error: Optional[Error125] = None
    errorDescription: Optional[ErrorDescription125] = None
